{% set name = "robotraconteur_companion" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/robotraconteur/robotraconteur_companion/archive/v{{ version }}.tar.gz
    sha256: 19878ca791ec44f14ed82829ec2aca0c6f191874b4a80eb31608b7320274845a
  - url: https://github.com/robotraconteur/robotraconteur_standard_robdef/archive/refs/tags/group1-v1.tar.gz
    sha256: aad4f122b1240756564d6f3d16258e3fd07febad9e0ceda489c5e32290e64707
    folder: robdef

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, min_pin='x.x.x') }}

requirements:
  build:
    - git
    - cmake
    - ninja  # [win]
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - librobotraconteur                      # [build_platform != target_platform]
  host:
    - librobotraconteur
    - libboost-devel
    - yaml-cpp
    - eigen
    - openssl  # [unix]
    - libopencv

test:
  commands:
    - test -f ${PREFIX}/include/RobotRaconteurCompanion/StdRobDef/StdRobDefAll.h  # [not win]
    - if exist %PREFIX%\\Library\\include\\RobotRaconteurCompanion\\StdRobDef\\StdRobDefAll.h (exit 0) else (exit 1)  # [win]
    - test -f ${PREFIX}/lib/libRobotRaconteurCompanion${SHLIB_EXT}  # [not win]
    - if exist %PREFIX%\\Library\\lib\\RobotRaconteurCompanion.lib (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\RobotRaconteurCompanion.dll (exit 0) else (exit 1)  # [win]

about:
  home: http://robotraconteur.com
  dev_url: https://github.com/robotraconteur/robotraconteur_companion
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Companion library for the Robot Raconteur core library'

extra:
  recipe-maintainers:
    - traversaro
    - Tobias-Fischer
    - johnwason
